---
language: python

python:
  - 2.7

services:
  - docker

sudo: required

env:
  matrix:
    - os=centos version=7 container_id=$(mktemp) ANSIBLE_VERSION=latest
    - os=centos version=7 container_id=$(mktemp) ANSIBLE_VERSION=2.4.0
    - os=centos version=7 container_id=$(mktemp) ANSIBLE_VERSION=2.4.3

install:
  - sudo docker pull ${os}:${version}
  - sudo docker build --file tests/travis/Dockerfile.${os}${version} --tag=${os}${version}:ansible tests/travis --build-arg ANSIBLE_VERSION=${ANSIBLE_VERSION}

script:
  - sudo docker run -dt --privileged --volume="${PWD}":/temp/ansible-yum-cron ${os}${version}:ansible /sbin/init > "${container_id}"

  - sudo docker exec -t "$(cat ${container_id})" ansible-playbook /temp/ansible-yum-cron/tests/test.yml -i /temp/ansible-yum-cron/tests/inventory --syntax-check
  - sudo docker exec -t "$(cat ${container_id})" ansible-playbook /temp/ansible-yum-cron/tests/test.yml -i /temp/ansible-yum-cron/tests/inventory -c local
  - sudo docker exec -t "$(cat ${container_id})" ansible-playbook /temp/ansible-yum-cron/tests/test.yml -i /temp/ansible-yum-cron/tests/inventory -c local | grep -q 'changed=0.*failed=0' && (echo "" && exit 0) || (echo 'Changed or failed after retry' && exit 1)

  - sudo docker exec -t "$(cat ${container_id})" cat /etc/yum/yum-cron.conf | grep "update_cmd = security"; if [ $? -ne 0 ]; then exit 1; fi
  - sudo docker exec -t "$(cat ${container_id})" cat /etc/yum/yum-cron.conf | grep "apply_updates = yes"; if [ $? -ne 0 ]; then exit 1; fi
  - sudo docker exec -t "$(cat ${container_id})" cat /etc/yum/yum-cron.conf | grep "email_to = root"; if [ $? -ne 0 ]; then exit 1; fi
  - sudo docker exec -t "$(cat ${container_id})" cat /etc/yum/yum-cron.conf | grep "assumeyes"; if [ $? -eq 0 ]; then exit 1; fi
  - sudo docker exec -t "$(cat ${container_id})" cat /etc/yum/yum-cron-hourly.conf | grep "update_cmd = minimal"; if [ $? -ne 0 ]; then exit 1; fi
  - sudo docker exec -t "$(cat ${container_id})" cat /etc/yum/yum-cron-hourly.conf | grep "download_updates = yes"; if [ $? -ne 0 ]; then exit 1; fi
  - sudo docker exec -t "$(cat ${container_id})" cat /etc/yum/yum-cron-hourly.conf | grep "apply_updates = no"; if [ $? -ne 0 ]; then exit 1; fi
  - sudo docker exec -t "$(cat ${container_id})" cat /etc/yum/yum-cron-hourly.conf | grep "assumeyes"; if [ $? -eq 0 ]; then exit 1; fi

after_script:
  - sudo docker stop "$(cat ${container_id})"

  - sudo docker rm "$(cat ${container_id})"

notification:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
