---
- name: Install yum-cron
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ shhirose_yum_cron_packages }}"
  tags:
    - yum-cron
    - install
    - system

- name: Copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ shhirose_yum_cron_config_files }}"
  tags:
    - yum-cron
    - install
    - system

#- import_tasks: "{{ ansible_service_mgr }}.yml"
- include_tasks: "{{ ansible_service_mgr }}.yml"
