---
- name: Install yum-cron
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ shhirose_yum_cron_packages }}"
  tags:
    - yum-cron
    - install
    - system

- name: Copy configuration files for RHEL v6
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ shhirose_yum_cron_config_files_RHELv6 }}"
  when: ansible_distribution_major_version == "6"
  tags:
    - yum-cron
    - install
    - system

- name: Copy configuration files for RHEL v7 or later
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ shhirose_yum_cron_config_files }}"
  when: ansible_distribution_major_version >= "7"
  tags:
    - yum-cron
    - install
    - system

- include_tasks: "{{ ansible_service_mgr }}.yml"
